# guideXOS bare-metal Mbed TLS 4.x build plan.
#
# Mbed TLS 4.x splits TLS/X.509 modules from the TF-PSA-Crypto dependency tree.
# This manifest verifies the imported layout and only enables the first
# freestanding compile pass when the required helper headers, TF-PSA-Crypto
# source roots, and guideXOS config pair are all present.

MBEDTLS_GUIDEXOS_IMPORT_ROOT := $(MBEDTLS_GUIDEXOS_REPO_ROOT)/third_party/mbedtls
MBEDTLS_GUIDEXOS_EXPECTED_MBEDTLS_VERSION := 4.1.0
MBEDTLS_GUIDEXOS_EXPECTED_TF_PSA_VERSION := 1.1.0
MBEDTLS_GUIDEXOS_INCLUDE_DIR := $(MBEDTLS_GUIDEXOS_IMPORT_ROOT)/include
MBEDTLS_GUIDEXOS_LIBRARY_DIR := $(MBEDTLS_GUIDEXOS_IMPORT_ROOT)/library
MBEDTLS_GUIDEXOS_TF_PSA_DIR := $(MBEDTLS_GUIDEXOS_IMPORT_ROOT)/tf-psa-crypto
MBEDTLS_GUIDEXOS_TF_PSA_CORE_DIR := $(MBEDTLS_GUIDEXOS_TF_PSA_DIR)/core
MBEDTLS_GUIDEXOS_TF_PSA_INCLUDE_DIR := $(MBEDTLS_GUIDEXOS_TF_PSA_DIR)/include
MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_INCLUDE_DIR := $(MBEDTLS_GUIDEXOS_TF_PSA_DIR)/drivers/builtin/include
MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR := $(MBEDTLS_GUIDEXOS_TF_PSA_DIR)/drivers/builtin/src
MBEDTLS_GUIDEXOS_TF_PSA_P256M_DIR := $(MBEDTLS_GUIDEXOS_TF_PSA_DIR)/drivers/p256-m
MBEDTLS_GUIDEXOS_TF_PSA_P256M_INCLUDE_DIR := $(MBEDTLS_GUIDEXOS_TF_PSA_P256M_DIR)/p256-m/include
MBEDTLS_GUIDEXOS_TF_PSA_P256M_INCLUDE_P256_DIR := $(MBEDTLS_GUIDEXOS_TF_PSA_P256M_INCLUDE_DIR)/p256-m
MBEDTLS_GUIDEXOS_TF_PSA_P256M_INTERFACE_DIR := $(MBEDTLS_GUIDEXOS_TF_PSA_P256M_DIR)/p256-m_driver_interface
MBEDTLS_GUIDEXOS_TF_PSA_DISPATCH_DIR := $(MBEDTLS_GUIDEXOS_TF_PSA_DIR)/dispatch
MBEDTLS_GUIDEXOS_TF_PSA_EXTRAS_DIR := $(MBEDTLS_GUIDEXOS_TF_PSA_DIR)/extras
MBEDTLS_GUIDEXOS_TF_PSA_PLATFORM_DIR := $(MBEDTLS_GUIDEXOS_TF_PSA_DIR)/platform
MBEDTLS_GUIDEXOS_TF_PSA_UTILITIES_DIR := $(MBEDTLS_GUIDEXOS_TF_PSA_DIR)/utilities
MBEDTLS_GUIDEXOS_CONFIG_HEADER := guidexos/mbedtls_config.h
MBEDTLS_GUIDEXOS_CRYPTO_CONFIG_HEADER := guidexos/crypto_config.h

MBEDTLS_GUIDEXOS_VERSION_HEADER := $(MBEDTLS_GUIDEXOS_INCLUDE_DIR)/mbedtls/version.h
MBEDTLS_GUIDEXOS_PLATFORM_HEADER := $(MBEDTLS_GUIDEXOS_TF_PSA_INCLUDE_DIR)/mbedtls/platform.h
MBEDTLS_GUIDEXOS_PLATFORM_UTIL_HEADER := $(MBEDTLS_GUIDEXOS_TF_PSA_INCLUDE_DIR)/mbedtls/platform_util.h
MBEDTLS_GUIDEXOS_CONSTANT_TIME_HEADER := $(MBEDTLS_GUIDEXOS_TF_PSA_INCLUDE_DIR)/mbedtls/constant_time.h
MBEDTLS_GUIDEXOS_PSA_UTIL_HEADER := $(MBEDTLS_GUIDEXOS_TF_PSA_INCLUDE_DIR)/mbedtls/psa_util.h
MBEDTLS_GUIDEXOS_MD_PSA_HEADER := $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/md_psa.h
MBEDTLS_GUIDEXOS_TF_PSA_BUILD_INFO := $(MBEDTLS_GUIDEXOS_TF_PSA_INCLUDE_DIR)/tf-psa-crypto/build_info.h
MBEDTLS_GUIDEXOS_TF_PSA_CRYPTO_CONFIG := $(MBEDTLS_GUIDEXOS_TF_PSA_INCLUDE_DIR)/psa/crypto_config.h
MBEDTLS_GUIDEXOS_TF_PSA_CORE := $(MBEDTLS_GUIDEXOS_TF_PSA_CORE_DIR)/psa_crypto.c
MBEDTLS_GUIDEXOS_TF_PSA_DRIVER_WRAPPERS := $(MBEDTLS_GUIDEXOS_TF_PSA_CORE_DIR)/psa_crypto_driver_wrappers.h
MBEDTLS_GUIDEXOS_MBEDTLS_CONFIG_CHECK := $(MBEDTLS_GUIDEXOS_LIBRARY_DIR)/mbedtls_config_check_before.h
MBEDTLS_GUIDEXOS_TF_PSA_CONFIG_CHECK := $(MBEDTLS_GUIDEXOS_TF_PSA_CORE_DIR)/tf_psa_crypto_config_check_before.h

MBEDTLS_GUIDEXOS_CFLAGS := -I$(MBEDTLS_GUIDEXOS_REPO_ROOT) -I$(MBEDTLS_GUIDEXOS_INCLUDE_DIR)
MBEDTLS_GUIDEXOS_CFLAGS += -I$(MBEDTLS_GUIDEXOS_LIBRARY_DIR)
MBEDTLS_GUIDEXOS_CFLAGS += -I$(MBEDTLS_GUIDEXOS_TF_PSA_DIR)
MBEDTLS_GUIDEXOS_CFLAGS += -I$(MBEDTLS_GUIDEXOS_TF_PSA_CORE_DIR)
MBEDTLS_GUIDEXOS_CFLAGS += -I$(MBEDTLS_GUIDEXOS_TF_PSA_INCLUDE_DIR)
MBEDTLS_GUIDEXOS_CFLAGS += -I$(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_INCLUDE_DIR)
MBEDTLS_GUIDEXOS_CFLAGS += -I$(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)
MBEDTLS_GUIDEXOS_CFLAGS += -I$(MBEDTLS_GUIDEXOS_TF_PSA_P256M_INCLUDE_DIR)
MBEDTLS_GUIDEXOS_CFLAGS += -I$(MBEDTLS_GUIDEXOS_TF_PSA_P256M_INCLUDE_P256_DIR)
MBEDTLS_GUIDEXOS_CFLAGS += -I$(MBEDTLS_GUIDEXOS_TF_PSA_P256M_INTERFACE_DIR)
MBEDTLS_GUIDEXOS_CFLAGS += -I$(MBEDTLS_GUIDEXOS_TF_PSA_DISPATCH_DIR)
MBEDTLS_GUIDEXOS_CFLAGS += -I$(MBEDTLS_GUIDEXOS_TF_PSA_EXTRAS_DIR)
MBEDTLS_GUIDEXOS_CFLAGS += -I$(MBEDTLS_GUIDEXOS_TF_PSA_PLATFORM_DIR)
MBEDTLS_GUIDEXOS_CFLAGS += -I$(MBEDTLS_GUIDEXOS_TF_PSA_UTILITIES_DIR)
MBEDTLS_GUIDEXOS_CFLAGS += -D_WIN32_WINNT=0x0500 -DEFIX64 -DMBEDTLS_TEST_SW_INET_PTON
MBEDTLS_GUIDEXOS_CFLAGS += -DMBEDTLS_CONFIG_FILE=\"$(MBEDTLS_GUIDEXOS_CONFIG_HEADER)\"
MBEDTLS_GUIDEXOS_CFLAGS += -DTF_PSA_CRYPTO_CONFIG_FILE=\"$(MBEDTLS_GUIDEXOS_CRYPTO_CONFIG_HEADER)\"

MBEDTLS_GUIDEXOS_MBEDTLS_C_SOURCES := \
    $(MBEDTLS_GUIDEXOS_LIBRARY_DIR)/mbedtls_config.c \
    $(MBEDTLS_GUIDEXOS_LIBRARY_DIR)/ssl_ciphersuites.c \
    $(MBEDTLS_GUIDEXOS_LIBRARY_DIR)/ssl_client.c \
    $(MBEDTLS_GUIDEXOS_LIBRARY_DIR)/ssl_msg.c \
    $(MBEDTLS_GUIDEXOS_LIBRARY_DIR)/ssl_tls.c \
    $(MBEDTLS_GUIDEXOS_LIBRARY_DIR)/ssl_tls12_client.c \
    $(MBEDTLS_GUIDEXOS_LIBRARY_DIR)/version.c \
    $(MBEDTLS_GUIDEXOS_LIBRARY_DIR)/x509.c \
    $(MBEDTLS_GUIDEXOS_LIBRARY_DIR)/x509_crt.c \
    $(MBEDTLS_GUIDEXOS_LIBRARY_DIR)/x509_oid.c

MBEDTLS_GUIDEXOS_TF_PSA_RUNTIME_C_SOURCES := \
    $(MBEDTLS_GUIDEXOS_TF_PSA_PLATFORM_DIR)/memory_buffer_alloc.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_PLATFORM_DIR)/platform.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_UTILITIES_DIR)/asn1parse.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_UTILITIES_DIR)/asn1write.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_UTILITIES_DIR)/base64.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_UTILITIES_DIR)/constant_time.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_UTILITIES_DIR)/oid.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_UTILITIES_DIR)/pem.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_EXTRAS_DIR)/md.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_EXTRAS_DIR)/pk.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_EXTRAS_DIR)/pk_ecc.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_EXTRAS_DIR)/pkparse.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_EXTRAS_DIR)/pk_rsa.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_EXTRAS_DIR)/pk_wrap.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/aes.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/bignum.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/bignum_core.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/bignum_mod.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/bignum_mod_raw.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/block_cipher.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/cipher.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/cipher_wrap.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/ecp.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/ecp_curves.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/ecdsa.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/gcm.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/psa_crypto_aead.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/psa_crypto_cipher.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/psa_crypto_ecp.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/psa_crypto_hash.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/psa_crypto_mac.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/psa_crypto_rsa.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/psa_util_internal.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/rsa.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/rsa_alt_helpers.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/sha256.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_BUILTIN_SRC_DIR)/sha512.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_P256M_DIR)/p256-m_driver_entrypoints.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_P256M_DIR)/p256-m/p256-m.c

MBEDTLS_GUIDEXOS_TF_PSA_C_SOURCES := \
    $(MBEDTLS_GUIDEXOS_TF_PSA_CORE_DIR)/psa_crypto.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_CORE_DIR)/psa_crypto_client.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_CORE_DIR)/psa_crypto_driver_wrappers_no_static.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_CORE_DIR)/psa_crypto_slot_management.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_CORE_DIR)/psa_crypto_storage.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_CORE_DIR)/psa_util.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_CORE_DIR)/tf_psa_crypto_config.c \
    $(MBEDTLS_GUIDEXOS_TF_PSA_CORE_DIR)/tf_psa_crypto_version.c

MBEDTLS_GUIDEXOS_LAYOUT_READY := 1
ifeq ($(wildcard $(MBEDTLS_GUIDEXOS_VERSION_HEADER)),)
MBEDTLS_GUIDEXOS_LAYOUT_READY := 0
endif
ifeq ($(wildcard $(MBEDTLS_GUIDEXOS_PLATFORM_HEADER)),)
MBEDTLS_GUIDEXOS_LAYOUT_READY := 0
endif
ifeq ($(wildcard $(MBEDTLS_GUIDEXOS_PLATFORM_UTIL_HEADER)),)
MBEDTLS_GUIDEXOS_LAYOUT_READY := 0
endif
ifeq ($(wildcard $(MBEDTLS_GUIDEXOS_CONSTANT_TIME_HEADER)),)
MBEDTLS_GUIDEXOS_LAYOUT_READY := 0
endif
ifeq ($(wildcard $(MBEDTLS_GUIDEXOS_PSA_UTIL_HEADER)),)
MBEDTLS_GUIDEXOS_LAYOUT_READY := 0
endif
ifeq ($(wildcard $(MBEDTLS_GUIDEXOS_MD_PSA_HEADER)),)
MBEDTLS_GUIDEXOS_LAYOUT_READY := 0
endif
ifeq ($(wildcard $(MBEDTLS_GUIDEXOS_TF_PSA_BUILD_INFO)),)
MBEDTLS_GUIDEXOS_LAYOUT_READY := 0
endif
ifeq ($(wildcard $(MBEDTLS_GUIDEXOS_TF_PSA_CRYPTO_CONFIG)),)
MBEDTLS_GUIDEXOS_LAYOUT_READY := 0
endif
ifeq ($(wildcard $(MBEDTLS_GUIDEXOS_TF_PSA_CORE)),)
MBEDTLS_GUIDEXOS_LAYOUT_READY := 0
endif
ifeq ($(wildcard $(MBEDTLS_GUIDEXOS_TF_PSA_DRIVER_WRAPPERS)),)
MBEDTLS_GUIDEXOS_LAYOUT_READY := 0
endif
ifeq ($(wildcard $(MBEDTLS_GUIDEXOS_MBEDTLS_CONFIG_CHECK)),)
MBEDTLS_GUIDEXOS_LAYOUT_READY := 0
endif
ifeq ($(wildcard $(MBEDTLS_GUIDEXOS_TF_PSA_CONFIG_CHECK)),)
MBEDTLS_GUIDEXOS_LAYOUT_READY := 0
endif
ifeq ($(wildcard $(MBEDTLS_GUIDEXOS_REPO_ROOT)/guidexos/mbedtls_config.h),)
MBEDTLS_GUIDEXOS_LAYOUT_READY := 0
endif
ifeq ($(wildcard $(MBEDTLS_GUIDEXOS_REPO_ROOT)/guidexos/crypto_config.h),)
MBEDTLS_GUIDEXOS_LAYOUT_READY := 0
endif

# When the 4.x layout is complete, run the first freestanding runtime-linked
# subset for TLS/X.509 prerequisite wiring. Navigator handshakes remain gated,
# but allocator hooks, PSA RNG/time callbacks, and one-shot CA parsing can now
# be exercised inside the kernel.
MBEDTLS_GUIDEXOS_COMPILE_READY := $(MBEDTLS_GUIDEXOS_LAYOUT_READY)
MBEDTLS_GUIDEXOS_LINK_READY := $(MBEDTLS_GUIDEXOS_LAYOUT_READY)
MBEDTLS_GUIDEXOS_COMPILE_PROBE_C_SOURCES := \
    $(if $(filter 1,$(MBEDTLS_GUIDEXOS_COMPILE_READY)), \
        $(MBEDTLS_GUIDEXOS_MBEDTLS_C_SOURCES) \
        $(MBEDTLS_GUIDEXOS_TF_PSA_RUNTIME_C_SOURCES) \
        $(MBEDTLS_GUIDEXOS_TF_PSA_C_SOURCES))
MBEDTLS_GUIDEXOS_C_SOURCES := \
    $(if $(filter 1,$(MBEDTLS_GUIDEXOS_LINK_READY)),$(MBEDTLS_GUIDEXOS_COMPILE_PROBE_C_SOURCES))
