# AMD64 Architecture Build Configuration
#
# Copyright (c) 2024 guideX
#

# Toolchain
CXX := x86_64-elf-g++
AS := nasm
LD := x86_64-elf-ld

# Architecture-specific flags
CFLAGS += -m64 -mcmodel=kernel -mno-red-zone -mno-mmx -mno-sse -mno-sse2
ASFLAGS := -f elf64
LIBS :=

# Target information
ARCH_BITS := 64
ARCH_NAME := AMD64
