#!/usr/bin/env python3
"""Generate embedded alpha atlases for guideXOS SystemFont."""

from pathlib import Path
import argparse
import textwrap

from PIL import Image


FONTS = [
    ("roboto_12pt_regular", "roboto_12pt_regular.png", 20, 20, 13, 8, 32, 126),
    ("roboto_12pt_bold", "roboto_12pt_bold.png", 20, 20, 13, 8, 32, 126),
    ("roboto_9pt_regular", "roboto_9pt_regular.png", 20, 20, 13, 8, 32, 126),
    ("roboto_9pt_bold", "roboto_9pt_bold.png", 20, 20, 13, 8, 32, 126),
]


def symbol_name(name: str) -> str:
    return "k" + "".join(part.capitalize() for part in name.split("_")) + "Alpha"


def format_bytes(values):
    lines = []
    for i in range(0, len(values), 24):
        lines.append("\t" + ", ".join(str(v) for v in values[i : i + 24]) + ",")
    return "\n".join(lines)


def load_alpha(path: Path):
    image = Image.open(path).convert("RGBA")
    alpha = list(image.getchannel("A").tobytes())
    return image.width, image.height, alpha


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font-dir", default="assets/Fonts/roboto", help="Roboto atlas PNG directory")
    parser.add_argument(
        "--output",
        default="kernel/core/include/kernel/generated/system_font_roboto.h",
        help="Generated C++ header path",
    )
    args = parser.parse_args()

    root = Path.cwd()
    font_dir = (root / args.font_dir).resolve()
    output = (root / args.output).resolve()

    chunks = [
        "// Generated by tools/generate_system_fonts.py. Do not edit by hand.",
        "#pragma once",
        "",
        "#if defined(GXOS_BARE_METAL)",
        '#include "../types.h"',
        "#else",
        "#include <cstdint>",
        "#endif",
        "",
        "namespace gxos {",
        "namespace gui {",
        "namespace generated {",
        "",
        "struct EmbeddedRobotoAtlas {",
        "\tconst char* name;",
        "\tconst uint8_t* alpha;",
        "\tuint16_t width;",
        "\tuint16_t height;",
        "\tuint16_t cellWidth;",
        "\tuint16_t cellHeight;",
        "\tuint8_t columns;",
        "\tuint8_t rows;",
        "\tuint8_t firstCodepoint;",
        "\tuint8_t lastCodepoint;",
        "};",
        "",
    ]

    descriptors = []
    for name, file_name, cell_w, cell_h, columns, rows, first_cp, last_cp in FONTS:
        width, height, alpha = load_alpha(font_dir / file_name)
        expected_w = cell_w * columns
        expected_h = cell_h * rows
        if (width, height) != (expected_w, expected_h):
            raise SystemExit(f"{file_name}: expected {expected_w}x{expected_h}, got {width}x{height}")
        sym = symbol_name(name)
        chunks.append(f"static const uint8_t {sym}[] = {{")
        chunks.append(format_bytes(alpha))
        chunks.append("};")
        chunks.append("")
        descriptor = "k" + "".join(part.capitalize() for part in name.split("_"))
        descriptors.append(descriptor)
        chunks.append(
            f'static const EmbeddedRobotoAtlas {descriptor} = {{"{name}", {sym}, '
            f"{width}, {height}, {cell_w}, {cell_h}, {columns}, {rows}, {first_cp}, {last_cp}}};"
        )
        chunks.append("")

    chunks.extend(
        [
            "static const EmbeddedRobotoAtlas* const kEmbeddedRobotoAtlases[] = {",
            textwrap.indent(",\n".join("&" + name for name in descriptors), "\t") + ",",
            "};",
            "",
            "} // namespace generated",
            "} // namespace gui",
            "} // namespace gxos",
            "",
        ]
    )

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(chunks), encoding="ascii", newline="\n")
    print(f"Wrote {output.relative_to(root)}")


if __name__ == "__main__":
    main()
